export const TAB_CHOSE = "TAB_CHOSE";

export const LOAD_PERSONNEL_SUCCESS = "LOAD_PERSONNEL_SUCCESS";
export const OPEN_PERSONNEL_MODAL = "OPEN_PERSONNEL_MODAL";
export const HANDLE_PERSONNEL_MODAL = "HANDLE_PERSONNEL_MODAL";
export const BEGIN_SAVE_PERSONNEL = "BEGIN_SAVE_PERSONNEL";
export const SAVE_PERSONNEL_SUCCESS = "SAVE_PERSONNEL_SUCCESS";
export const DISPLAY_GLOBAL_LOADING = "DISPLAY_GLOBAL_LOADING";
export const HIDE_GLOBAL_LOADING = "HIDE_GLOBAL_LOADING";

export const LOAD_ROOM_SUCCESS = "LOAD_ROOM_SUCCESS";
export const OPEN_ROOM_MODAL = "OPEN_ROOM_MODAL";
export const HANDLE_ROOM_MODAL = "HANDLE_ROOM_MODAL";
export const BEGIN_SAVE_ROOM = "BEGIN_SAVE_ROOM";
export const SAVE_ROOM_SUCCESS = "SAVE_ROOM_SUCCESS";

export const LOAD_MEETING_SUCCESS = "LOAD_MEETING_SUCCESS";
export const OPEN_MEETING_MODAL = "OPEN_MEETING_MODAL";
export const HANDLE_MEETING_MODAL = "HANDLE_MEETING_MODAL";
export const BEGIN_SAVE_MEETING = "BEGIN_SAVE_MEETING";
export const SAVE_MEETING_SUCCESS = "SAVE_MEETING_SUCCESS";

export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const OPEN_DETAIL_MODAL = "OPEN_DETAIL_MODAL";
export const HANDLE_DETAIL_MODAL = "HANDLE_DETAIL_MODAL";
export const BEGIN_SAVE_DETAIL = "BEGIN_SAVE_DETAIL";
export const SAVE_DETAIL_SUCCESS = "SAVE_DETAIL_SUCCESS";
